


#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/LevanDemo
#    username: postgres
#    password: damiane1997
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#security:
#  jwt:
#    expiration-minutes: 60
#    secret-key: dGhpcyBpcyBteSBzZWN1cmUga2V5IGFuZCB5b3UgY2Fubm90IGhhY2sgaXQ=


#spring:
#  datasource:
#    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#security:
#  jwt:
#    expiration-minutes: 60
#    secret-key: ${JWT_SECRET_KEY}



spring:
  datasource:
    url: jdbc:postgresql://meticulous-empathy.railway.internal:5432/railway
    username: postgres
    password: aQKxJhFGNthadZVimlKNwPrXrUiHKpEi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    expiration-minutes: 60
    secret-key: dGhpcyBpcyBteSBzZWN1cmUga2V5IGFuZCB5b3UgY2Fubm90IGhhY2sgaXQ=
